### ISSUE TITLE
Instructions on how to install?

### ISSUE THREAD

**Issue by gCurtisCT** [StanDog/npp-zoomdisabler#1]
All I get is a .dll. What do I do with this?

**Comment by StanDog** [comment]
Like with every Notepad++ plugin you have to place the DLL file in the "plugins" subdirectory of your Notepad++ installation (by default copy to: **C:\Program Files (x86)\Notepad++\plugins\**).

**Comment by gCurtisCT** [comment]
Thanks. For all other plugins I've just used the plugin manager to install them, so I've never had to put any .dlls anywhere.

**Comment by StanDog** [comment]
The plugin can also be installed through the Plugin Manager but we have moved recently from SourceForge to GitHub and therefore it takes a while until it works again via the Plugin Manager.
